neo4j-shell -c "schema ls"
neo4j-shell -c "explain MATCH (Company:Company{companyName:'Cmp_#'})-[x:CMP2DRG]->(Drug)<-[r:TRL2DRG1]-(Trial)-[z:TRL2DRG2]->(anotherDrug) RETURN Company,Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (Drug:Drug{drugName:'Drg_#'})<-[r:TRL2DRG1]-(Trial)-[z:RELATED_TO]->(anotherDrug) RETURN Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (Company:Company{attr1:'asqwdasdasda'})-[x:CMP2DRG]->(Drug)<-[r:TRL2DRG2]-(Trial)-[z:TRL2DRG1]->(anotherDrug) RETURN Company,Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (Company:Company{attr9:'asqwdasdasda'})-[x:CMP2DRG]->(Drug)<-[r:TRL2DRG1]-(Trial)-[z:TRL2DRG2]->(anotherDrug) RETURN Company,Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (Drug:Drug{attr1:'asqwdasdasda'})<-[r:TRL2DRG2]-(Trial)-[z:TRL2DRG3]->(anotherDrug) RETURN Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (Drug:Drug{attr9:'asqwdasdasda'})<-[r:TRL2DRG3]-(Trial)-[z:TRL2DRG1]->(anotherDrug) RETURN Drug,Trial,anotherDrug ;"
neo4j-shell -c "explain MATCH (n:Company) RETURN n LIMIT 2;"
neo4j-shell -c "explain MATCH (n:Drug{drugName:'Drg_1'}) RETURN n;"
neo4j-shell -c "explain MATCH (n:Company{companyName:'Cmp_1'}) RETURN n;"
neo4j-shell -c "explain MATCH n RETURN n LIMIT 2;"